
-- DQL -> Data Query Operations (SELECT)

create database DQL_Database

USE DQL_Database;

-- PARENT TABLE
CREATE TABLE DEPARTMENT (
	DEPT_NO INT PRIMARY KEY,
	DEPT_NAME VARCHAR(100) NOT NULL UNIQUE,
	DEPT_LOC NVARCHAR(150) NOT NULL UNIQUE
	);

INSERT INTO DEPARTMENT 
VALUES (10,'ACCOUNTING','NEW YORK'),
	(20,'RESEARCH','DALLAS'),
	(30,'SALES','CHICAGO'),
	(40,'OPEARTIONS','BOSTON')

SELECT * FROM DEPARTMENT;

-- CHILD TABLE
CREATE TABLE EMPLOYEES (
	EMP_ID INT PRIMARY KEY,
	EMP_NAME VARCHAR(100) NOT NULL,
	JOB VARCHAR(10) NOT NULL,
	MGR_ID INT NOT NULL,
	HIREDATE DATE NOT NULL,
	SAL DECIMAL(7,2) NOT NULL,
	COMMISSION INT,
	DEPT_NO INT,
	CONSTRAINT FRK_DEPT_NO FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO)
	);

INSERT INTO EMPLOYEES(EMP_ID,EMP_NAME,JOB,MGR_ID,HIREDATE,SAL,COMMISSION,DEPT_NO)
VALUES (7369,'SMITH','CLERK',7902,'1980-DEC-17',800,300,20)

SELECT * FROM DEPARTMENT

SELECT * FROM EMPLOYEES

DELETE FROM EMPLOYEES
WHERE EMP_ID = 7361

SELECT * FROM DEPARTMENT
where DEPT_NO = 10

SELECT * FROM DEPARTMENT
where DEPT_NO IN (20,40)

SELECT * FROM DEPARTMENT
where DEPT_NAME like '%AL%' or DEPT_NAME like '%art%'

SELECT * FROM DEPARTMENT
where DEPT_NAME like '[a-o][0-9a-d]%'


SELECT * FROM DEPARTMENT


TRUNCATE TABLE DEPARTMENT

TRUNCATE TABLE EMPLOYESS

DROP TABLE IF EXISTS DEPARTMENT


-- ---------------------------


	----------------------------------------------------------












